import Logo from "./extensions/favicon.svg";
import favicon from "./extensions/favicon.svg";

export default {
  config: {
    locales: ["en"],
    translations: {
      en: {
        "app.components.LeftMenu.navbrand.title": "DOWNLOAD A CAR",
        "app.components.LeftMenu.navbrand.workplace": "engineered by Outdated",
        "Auth.form.welcome.subtitle": "Welcome to the DOWNLOAD A CAR",
        "Auth.form.username.placeholder": "e.g. outdated",
        "Content Manager": "Content Editor",
        "HomePage.helmet.title": "DOWNLOAD A CAR",
        "Auth.form.email.placeholder": "e.g. outdated@teamparallel.gg",
        "Auth.form.firstname.placeholder": "e.g. Danny",
        "Auth.form.lastname.placeholder": "e.g. Parallel",
        "HomePage.welcome.congrats.content":
          "Welcome to the DOWNLOAD A CAR Backend.",
        "HomePage.welcome.congrats.content.bold": "",
        "Media Library": "Assets",
        "New entry": "New",
        "app.components.MarketplaceBanner.image.alt": "DOWNLOAD A CAR ",
        "Content Type Builder": "Content-Types Builder — DO NOT EDIT",
      },
    },
    auth: {
      logo: Logo,
    },
    head: {
      favicon: favicon,
    },
    menu: {
      logo: Logo,
    },
    head: {},
    tutorials: false,
    notifications: { release: false },
    theme: {
      sizes: {
        borderRadius: "5px",
      },
      colors: {
        alternative100: "#ffffff",
        alternative200: "#e6e6e6",
        alternative500: "#cccccc",
        alternative600: "#b3b3b3",
        alternative700: "#999999",
        danger100: "#fcecea",
        danger200: "#f5c0b8",
        danger500: "#ee5e52",
        danger600: "#d02b20",
        danger700: "#b72b1a",
        neutral0: "#000000",
        neutral100: "#1a1a1a",
        neutral1000: "#333333",
        neutral150: "#4d4d4d",
        neutral200: "#666666",
        neutral300: "#808080",
        neutral400: "#999999",
        neutral500: "#b3b3b3",
        neutral600: "#cccccc",
        neutral700: "#e6e6e6",
        neutral800: "#ffffff",
        neutral900: "#ffffff",
        primary100: "#ffffff",
        primary200: "#e6e6e6",
        primary500: "#cccccc",
        primary600: "#b3b3b3",
        primary700: "#808080",
        secondary100: "#eaf5ff",
        secondary200: "#b8e1ff",
        secondary500: "#66b7f1",
        secondary600: "#0c75af",
        secondary700: "#006096",
        success100: "#eafbe7",
        success200: "#c6f0c2",
        success500: "#5cb176",
        success600: "#328048",
        success700: "#2f6846",
        warning100: "#fdf4dc",
        warning200: "#fae7b9",
        warning500: "#f29d41",
        warning600: "#d9822f",
        warning700: "#be5d01",
      },
    },
  },

  bootstrap() {},
};
